### PR TITLE
Updates of the fix

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
I was working on this fix too. I merged our codes. Just a few changes.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
#21356

**Comment by aochagavia** [comment]
The only difference is the style, isn't it? I think the meaning of the code doesn't change.

**Comment by GuillaumeGomez** [comment]
I found my code a little more Rust-like (I avoid to use return as much as possible). I created an else case for this reason.

**Comment by aochagavia** [comment]
I could merge this, but then the code would need to be reviewed again (at this moment it has already been approved). Personally I don't think it's worth it.

I think it is great to improve the style... The code in the compiler is just a big mix of styles at this moment. Maybe you could open a PR to address this issue more generally (i.e. not only for this function)

**Comment by GuillaumeGomez** [comment]
Hum... Why not... If you close this one I'll do that.

**Comment by aochagavia** [comment]
Great!

**Pull request closed without merging**
